language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-support
    - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

before_install:
  - yes | sdkmanager --licenses

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
